//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisambievBulat321_Pets.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public string ID { get; set; }
        public string Image { get; set; }
        public Nullable<int> Pet { get; set; }
        public string Description { get; set; }
    
        public virtual Pets Pets { get; set; }
    }
}
